### PR TITLE
Add build_fcitx_bazel scripts

### PR DESCRIPTION
**Pull request by phoepsilonix**
## Description
Add build_fcitx_bazel scripts
change script of fcitx4's workflow

### CODE REVIEW

**Comment by wengxt** [comment]
you definitely break the build by remove @fcitx

**Comment by phoepsilonix** [comment]
> you definitely break the build by remove @fcitx

I certainly thought so too, but in my environment, when @fcitx is present, bazel cannot find fcitx and an error occurs, and when I remove @fcitx, the build can be completed to the end. I am trying to build with fcitx and fcitx-qt6 installed. I thought that bazel's reaction was different due to the description of pkg-config or something, but is there something wrong with my environment? I am trying to build in multiple environments, such as podman, but...

**Comment by wengxt** [comment]
No, the pkg-config should just work.

I even used a non standard prefix to test.

**Comment by phoepsilonix** [comment]
Of course, pkg-config is working. Bazel should have the library information for fcitx-mozc to link against.
The difference with fcitx5 is that fcitx can usually be compiled with -I/usr/include. For fcitx, pkg-config doesn't need to show cflags unless you use --keep-system-cflags to include headers.

So I suspect it's being handled differently.

**Comment by phoepsilonix** [comment]
```
bazel cquery --config oss_linux --config release_build  "deps(//unix/fcitx:fcitx-mozc.so)" --output graph > specific_deps.dot
Computing main repo mapping: 
Loading: 
Loading: 0 packages loaded
Analyzing: target //unix/fcitx:fcitx-mozc.so (1 packages loaded, 0 targets configured)
ERROR: Traceback (most recent call last):
	File "/home/phoepsilonix/.cache/bazel/_bazel_phoepsilonix/a422ec5eb6e7740277eb4ee8963a4986/external/_main~_repo_rules~fcitx/BUILD.bazel", line 8, column 16, in <toplevel>
		hdrs = glob([
Error in glob: pattern cannot be absolute
ERROR: /home/phoepsilonix/.cache/bazel/_bazel_phoepsilonix/a422ec5eb6e7740277eb4ee8963a4986/external/_main~_repo_rules~fcitx/BUILD.bazel: no such target '@@_main~_repo_rules~fcitx//:fcitx': target 'fcitx' not declared in package '' defined by /home/phoepsilonix/.cache/bazel/_bazel_phoepsilonix/a422ec5eb6e7740277eb4ee8963a4986/external/_main~_repo_rules~fcitx/BUILD.bazel
ERROR: /home/phoepsilonix/work/aur/mozc-with-jp-dict/src/mozc/src/unix/fcitx/BUILD.bazel:89:15: no such target '@@_main~_repo_rules~fcitx//:fcitx': target 'fcitx' not declared in package '' defined by /home/phoepsilonix/.cache/bazel/_bazel_phoepsilonix/a422ec5eb6e7740277eb4ee8963a4986/external/_main~_repo_rules~fcitx/BUILD.bazel and referenced by '//unix/fcitx:fcitx-mozc.so'
ERROR: Analysis of target '//unix/fcitx:fcitx-mozc.so' failed; build aborted: Analysis failed
INFO: Elapsed time: 0.098s
INFO: 0 processes.
ERROR: Build did NOT complete successfully
```

when remove `@fcitx`
```
 bazel cquery --config oss_linux --config release_build  "deps(//unix/fcitx:fcitx-mozc.so)" --output graph > specific_deps.dot
Computing main repo mapping: 
Loading: 
Loading: 0 packages loaded
Analyzing: target //unix/fcitx:fcitx-mozc.so (1 packages loaded, 0 targets configured)
INFO: Analyzed target //unix/fcitx:fcitx-mozc.so (1 packages loaded, 18 targets configured).
INFO: Found 1 target...
INFO: Elapsed time: 0.318s, Critical Path: 0.00s
INFO: 0 processes.
INFO: Build completed successfully, 0 total actions
```
```
-  "//unix/fcitx:fcitx-mozc.so (914686d)"
  "//unix/fcitx:fcitx-mozc.so (914686d)" -> "//:compiler_msvc_like (914686d)"
  "//unix/fcitx:fcitx-mozc.so (914686d)" -> "//:macro (914686d)"
  "//unix/fcitx:fcitx-mozc.so (914686d)" -> "//base:init_mozc (914686d)"
  "//unix/fcitx:fcitx-mozc.so (914686d)" -> "//unix/fcitx:eim.cc (null)"
  "//unix/fcitx:fcitx-mozc.so (914686d)" -> "//unix/fcitx:fcitx_mozc (914686d)"
  "//unix/fcitx:fcitx-mozc.so (914686d)" -> "@bazel_tools//tools:host_platform (914686d)\n@bazel_tools//tools:host_platform (ab8cba1)"
  "//unix/fcitx:fcitx-mozc.so (914686d)" -> "@bazel_tools//tools/cpp:current_cc_toolchain (914686d)"
  "//unix/fcitx:fcitx-mozc.so (914686d)" -> "@bazel_tools//tools/cpp:link_extra_lib (914686d)"
  "//unix/fcitx:fcitx-mozc.so (914686d)" -> "@bazel_tools//tools/cpp:malloc (914686d)"
  "//unix/fcitx:fcitx-mozc.so (914686d)" -> "@bazel_tools//tools/cpp:toolchain_type (914686d)"
  "//unix/fcitx:fcitx-mozc.so (914686d)" -> "@bazel_tools//tools/def_parser:def_parser (f9c3c74)"
  "//unix/fcitx:fcitx-mozc.so (914686d)" -> "@@bazel_tools~cc_configure_extension~local_config_cc//:cc-compiler-k8 (914686d)"
  "//unix/fcitx:fcitx-mozc.so (914686d)" -> "@platforms//host:host (ab8cba1)"
  "//unix/fcitx:fcitx_mozc (914686d)"
  "//unix/fcitx:fcitx_mozc (914686d)" -> "//:compiler_msvc_like (914686d)"
  "//unix/fcitx:fcitx_mozc (914686d)" -> "//:macro (914686d)"
  "//unix/fcitx:fcitx_mozc (914686d)" -> "//base:port (914686d)"
  "//unix/fcitx:fcitx_mozc (914686d)" -> "//base:process (914686d)"
  "//unix/fcitx:fcitx_mozc (914686d)" -> "//base:run_level (914686d)"
  "//unix/fcitx:fcitx_mozc (914686d)" -> "//base:util (914686d)"
  "//unix/fcitx:fcitx_mozc (914686d)" -> "//base:vlog (914686d)"
  "//unix/fcitx:fcitx_mozc (914686d)" -> "//client:client_interface (914686d)"
  "//unix/fcitx:fcitx_mozc (914686d)" -> "//protocol:commands_cc_proto (914686d)"
  "//unix/fcitx:fcitx_mozc (914686d)" -> "//unix/fcitx:fcitx_key_util (914686d)"
  "//unix/fcitx:fcitx_mozc (914686d)" -> "//unix/fcitx:fcitx_mozc.cc (null)\n//unix/fcitx:fcitx_mozc.h (null)\n//unix/fcitx:mozc_response_parser.cc (null)\n//unix/fcitx:mozc_response_parser.h (null)"
  "//unix/fcitx:fcitx_mozc (914686d)" -> "//unix/fcitx:mozc_connection (914686d)"
  "//unix/fcitx:fcitx_mozc (914686d)" -> "//unix/fcitx:surrounding_text_util (914686d)"
  "//unix/fcitx:fcitx_mozc (914686d)" -> "@com_google_absl//absl/log:check (914686d)"
  "//unix/fcitx:fcitx_mozc (914686d)" -> "@bazel_tools//tools:host_platform (914686d)\n@bazel_tools//tools:host_platform (ab8cba1)"
  "//unix/fcitx:fcitx_mozc (914686d)" -> "@bazel_tools//tools/cpp:current_cc_toolchain (914686d)"
  "//unix/fcitx:fcitx_mozc (914686d)" -> "@bazel_tools//tools/cpp:toolchain_type (914686d)"
  "//unix/fcitx:fcitx_mozc (914686d)" -> "@bazel_tools//tools/def_parser:def_parser (f9c3c74)"
  "//unix/fcitx:fcitx_mozc (914686d)" -> "@@bazel_tools~cc_configure_extension~local_config_cc//:cc-compiler-k8 (914686d)"
  "//unix/fcitx:fcitx_mozc (914686d)" -> "@platforms//host:host (ab8cba1)"
  "//unix/fcitx:mozc_connection (914686d)"
  "//unix/fcitx:mozc_connection (914686d)" -> "//:compiler_msvc_like (914686d)"
  "//unix/fcitx:mozc_connection (914686d)" -> "//:macro (914686d)"
  "//unix/fcitx:mozc_connection (914686d)" -> "//base:port (914686d)"
  "//unix/fcitx:mozc_connection (914686d)" -> "//base:util (914686d)"
  "//unix/fcitx:mozc_connection (914686d)" -> "//base:vlog (914686d)"
  "//unix/fcitx:mozc_connection (914686d)" -> "//client:client (914686d)"
  "//unix/fcitx:mozc_connection (914686d)" -> "//protocol:commands_cc_proto (914686d)"
  "//unix/fcitx:mozc_connection (914686d)" -> "//unix/fcitx:fcitx_key_util (914686d)"
  "//unix/fcitx:mozc_connection (914686d)" -> "//unix/fcitx:mozc_connection.cc (null)\n//unix/fcitx:mozc_connection.h (null)"
  "//unix/fcitx:mozc_connection (914686d)" -> "//unix/fcitx:surrounding_text_util (914686d)"
  "//unix/fcitx:mozc_connection (914686d)" -> "@com_google_absl//absl/log:check (914686d)"
  "//unix/fcitx:mozc_connection (914686d)" -> "@bazel_tools//tools:host_platform (914686d)\n@bazel_tools//tools:host_platform (ab8cba1)"
  "//unix/fcitx:mozc_connection (914686d)" -> "@bazel_tools//tools/cpp:current_cc_toolchain (914686d)"
  "//unix/fcitx:mozc_connection (914686d)" -> "@bazel_tools//tools/cpp:toolchain_type (914686d)"
  "//unix/fcitx:mozc_connection (914686d)" -> "@bazel_tools//tools/def_parser:def_parser (f9c3c74)"
  "//unix/fcitx:mozc_connection (914686d)" -> "@@bazel_tools~cc_configure_extension~local_config_cc//:cc-compiler-k8 (914686d)"
  "//unix/fcitx:mozc_connection (914686d)" -> "@platforms//host:host (ab8cba1)"
  "//unix/fcitx:surrounding_text_util (914686d)"
  "//unix/fcitx:surrounding_text_util (914686d)" -> "//:compiler_msvc_like (914686d)"
  "//unix/fcitx:surrounding_text_util (914686d)" -> "//:macro (914686d)"
  "//unix/fcitx:surrounding_text_util (914686d)" -> "//base:port (914686d)"
  "//unix/fcitx:surrounding_text_util (914686d)" -> "//base:util (914686d)"
  "//unix/fcitx:surrounding_text_util (914686d)" -> "//base:vlog (914686d)"
  "//unix/fcitx:surrounding_text_util (914686d)" -> "//unix/fcitx:surrounding_text_util.cc (null)\n//unix/fcitx:surrounding_text_util.h (null)"
  "//unix/fcitx:surrounding_text_util (914686d)" -> "@com_google_absl//absl/log:check (914686d)"
  "//unix/fcitx:surrounding_text_util (914686d)" -> "@bazel_tools//tools:host_platform (914686d)\n@bazel_tools//tools:host_platform (ab8cba1)"
  "//unix/fcitx:surrounding_text_util (914686d)" -> "@bazel_tools//tools/cpp:current_cc_toolchain (914686d)"
  "//unix/fcitx:surrounding_text_util (914686d)" -> "@bazel_tools//tools/cpp:toolchain_type (914686d)"
  "//unix/fcitx:surrounding_text_util (914686d)" -> "@bazel_tools//tools/def_parser:def_parser (f9c3c74)"
  "//unix/fcitx:surrounding_text_util (914686d)" -> "@@bazel_tools~cc_configure_extension~local_config_cc//:cc-compiler-k8 (914686d)"
  "//unix/fcitx:surrounding_text_util (914686d)" -> "@platforms//host:host (ab8cba1)"
  "//unix/fcitx:surrounding_text_util.cc (null)\n//unix/fcitx:surrounding_text_util.h (null)"
  "//unix/fcitx:mozc_connection.cc (null)\n//unix/fcitx:mozc_connection.h (null)"
  "//unix/fcitx:fcitx_mozc.cc (null)\n//unix/fcitx:fcitx_mozc.h (null)\n//unix/fcitx:mozc_response_parser.cc (null)\n//unix/fcitx:mozc_response_parser.h (null)"
  "//unix/fcitx:fcitx_key_util (914686d)"
  "//unix/fcitx:fcitx_key_util (914686d)" -> "//:compiler_msvc_like (914686d)"
  "//unix/fcitx:fcitx_key_util (914686d)" -> "//:macro (914686d)"
  "//unix/fcitx:fcitx_key_util (914686d)" -> "//base:port (914686d)"
  "//unix/fcitx:fcitx_key_util (914686d)" -> "//base:singleton (914686d)"
  "//unix/fcitx:fcitx_key_util (914686d)" -> "//base:vlog (914686d)"
  "//unix/fcitx:fcitx_key_util (914686d)" -> "//protocol:commands_cc_proto (914686d)"
  "//unix/fcitx:fcitx_key_util (914686d)" -> "//protocol:config_cc_proto (914686d)"
  "//unix/fcitx:fcitx_key_util (914686d)" -> "//unix/fcitx:fcitx_key_event_handler.cc (null)\n//unix/fcitx:fcitx_key_event_handler.h (null)\n//unix/fcitx:fcitx_key_translator.cc (null)\n//unix/fcitx:fcitx_key_translator.h (null)"
  "//unix/fcitx:fcitx_key_util (914686d)" -> "@com_google_absl//absl/log:check (914686d)"
  "//unix/fcitx:fcitx_key_util (914686d)" -> "@bazel_tools//tools:host_platform (914686d)\n@bazel_tools//tools:host_platform (ab8cba1)"
  "//unix/fcitx:fcitx_key_util (914686d)" -> "@bazel_tools//tools/cpp:current_cc_toolchain (914686d)"
  "//unix/fcitx:fcitx_key_util (914686d)" -> "@bazel_tools//tools/cpp:toolchain_type (914686d)"
  "//unix/fcitx:fcitx_key_util (914686d)" -> "@bazel_tools//tools/def_parser:def_parser (f9c3c74)"
  "//unix/fcitx:fcitx_key_util (914686d)" -> "@@bazel_tools~cc_configure_extension~local_config_cc//:cc-compiler-k8 (914686d)"
  "//unix/fcitx:fcitx_key_util (914686d)" -> "@platforms//host:host (ab8cba1)"
  "//unix/fcitx:fcitx_key_event_handler.cc (null)\n//unix/fcitx:fcitx_key_event_handler.h (null)\n//unix/fcitx:fcitx_key_translator.cc (null)\n//unix/fcitx:fcitx_key_translator.h (null)"
  "//unix/fcitx:eim.cc (null)"
```

**Comment by phoepsilonix** [comment]
<fcitx/ime.h> referenced by unix/fcitx/fcitx_key_translator.h cannot be found, but is resolved by -I/usr/include.

**Comment by phoepsilonix** [comment]
.cache/bazel/_bazel_phoepsilonix/a422ec5eb6e7740277eb4ee8963a4986/external/_main~_repo_rules~fcitx/BUILD.bazel

```
package(
    default_visibility = ["//visibility:public"],
)

cc_library(
    name = "fcitx",
    hdrs = glob([
        "/**"
    ]),
    copts = [
        ""
    ],
    includes = [
        ""
    ],
    linkopts = [
        ""
    ],
)

exports_files(glob(["libexec/*"]))
```

**Comment by phoepsilonix** [comment]
It seems like the absolute path here is the problem. I wonder if the pkg-config setting can be worked around by setting it in the BUILD file?

```
    hdrs = glob([
        "/**"
    ]),
```

**Comment by phoepsilonix** [comment]
This may not be possible without modifying bazel/pkg_config_repository.bzl.

**Comment by phoepsilonix** [comment]
Here are some workarounds I can think of.

Workaround 1
First add -I/usr/include/fcitx as a dummy to the fcitx.pc file for pkg-config.
Bazel will recognize usr/include/fcitx and enable @fcitx as a module.
```sh
cat /usr/lib/pkgconfig/fcitx.pc 
```
```
prefix=/usr
exec_prefix=/usr
libdir=/usr/lib
includedir=/usr/include

Name: fcitx
Description: Fcitx - Free Chinese Input Toy of X
Version: 4.2.9.9
Requires: fcitx-config
Cflags: -I/usr/include/fcitx -I/usr/include
Libs: -L/usr/lib -lfcitx-core
```

Workaround 2
Create a separate process for fcitx that is equivalent to bazel/pkg_config_repository.bzl.

Workaround 3
Modify bazel/pkg_config_repository.bzl

**Comment by phoepsilonix** [comment]
It seems we can make Bazel recognize @fcitx using one of these three methods.
Do you have a preferred approach?

**Comment by phoepsilonix** [comment]
If https://github.com/google/mozc/pull/1095 is approved for merging, this (#68) will no longer be necessary.

**Comment by wengxt** [comment]
Ok, it seems that its some issue with /usr/include 

So we can try something else for fcitx anyway.

fcitx5 is not affected since it has an additonal layer of directory

**Comment by phoepsilonix** [comment]
Once google#1095 is merged, it will become an unnecessary PR, so I will change it to a PR that adds build_fcitx_bazel.

**Comment by phoepsilonix** [comment]
https://github.com/google/mozc/pull/1095#issuecomment-2443502005

**Comment by phoepsilonix** [comment]
It seems that pkg-config --libs fcitx does not require it by default, so "usr/include/fcitx-gclient" may not be necessary.

**Comment by wengxt** [comment]
Please use this new script in the fcitx4 workflow

**Comment by phoepsilonix** [comment]
I understand.

**Comment by wengxt** [comment]
...errr

You can push more commit to your branch and make the modification directly?..

**Comment by phoepsilonix** [comment]
OK

**Comment by phoepsilonix** [comment]
Ok

**Comment by phoepsilonix** [comment]
hmm

**Comment by phoepsilonix** [comment]
Reopen ?

**Comment by phoepsilonix** [comment]
I made changes to the workflow but can't reopen the PR.

**Comment by phoepsilonix** [comment]
It seemed to be okay

**Pull request merged**
